#CONFIGURATION = Debug
CONFIGURATION = Release

all: build_xcode

clean: clean_builds

run: all
	./build_xcode/build/Release/ShowyEdge-Preferences.app/Contents/MacOS/ShowyEdge-Preferences

include ../Makefile.rules
