name: ShowyEdge CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive
      - name: brew install
        run: brew install xcodegen
      - name: test
        run: make test
      - name: package
        run: make clean build
